package com.cmiot.rms.dao.mapper;

import com.cmiot.rms.dao.model.BoxBusinessExecuteHistory;

import java.util.List;

import org.apache.ibatis.annotations.Insert;

public interface BoxBusinessExecuteHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gateway_business_execute_history
     *
     * @mbggenerated
     */
    @Insert({
        "insert into t_box_business_execute_history (order_no, execute_time, ",
        "execute_status)",
        "values (#{orderNo,jdbcType=VARCHAR}, #{executeTime,jdbcType=INTEGER}, ",
        "#{executeStatus,jdbcType=INTEGER})"
    })
    int insert(BoxBusinessExecuteHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gateway_business_execute_history
     *
     * @mbggenerated
     */
    int insertSelective(BoxBusinessExecuteHistory record);
    
    
    List<BoxBusinessExecuteHistory> queryExecuteHisotry(String orderNo);
}