package com.cmiot.rms.dao.mapper;

import org.apache.ibatis.annotations.*;

import com.cmiot.rms.dao.model.BoxBusinessTemplateRelation;

import java.util.List;
import java.util.Map;

public interface BoxBusinessTemplateRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business_template_relation
     *
     * @mbggenerated
     */
    @Delete({
        "delete from t_box_business_template_relation",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business_template_relation
     *
     * @mbggenerated
     */
    @Insert({
        "insert into t_box_business_template_relation (id, manufacturerID, ",
        "manufacturer_name, factoryID, ",
        "factory_name, box_model, ",
        "hd_version, firmware_version, ",
        "business_template, bussiness_code)",
        "values (#{id,jdbcType=VARCHAR}, #{manufacturerid,jdbcType=VARCHAR}, ",
        "#{manufacturerName,jdbcType=VARCHAR}, #{factoryid,jdbcType=VARCHAR}, ",
        "#{factoryName,jdbcType=VARCHAR}, #{boxModel,jdbcType=VARCHAR}, ",
        "#{hdVersion,jdbcType=VARCHAR}, #{firmwareVersion,jdbcType=VARCHAR}, ",
        "#{businessTemplate,jdbcType=VARCHAR}, #{bussinessCode,jdbcType=VARCHAR})"
    })
    int insert(BoxBusinessTemplateRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business_template_relation
     *
     * @mbggenerated
     */
    int insertSelective(BoxBusinessTemplateRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business_template_relation
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, manufacturerID, manufacturer_name, factoryID, factory_name, box_model, ",
        "hd_version, firmware_version, business_template, bussiness_code",
        "from t_business_template_relation",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    BoxBusinessTemplateRelation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business_template_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BoxBusinessTemplateRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business_template_relation
     *
     * @mbggenerated
     */
    @Update({
        "update t_business_template_relation",
        "set manufacturerID = #{manufacturerid,jdbcType=VARCHAR},",
          "manufacturer_name = #{manufacturerName,jdbcType=VARCHAR},",
          "factoryID = #{factoryid,jdbcType=VARCHAR},",
          "factory_name = #{factoryName,jdbcType=VARCHAR},",
          "box_model = #{boxModel,jdbcType=VARCHAR},",
          "hd_version = #{hdVersion,jdbcType=VARCHAR},",
          "firmware_version = #{firmwareVersion,jdbcType=VARCHAR},",
          "business_template = #{businessTemplate,jdbcType=VARCHAR},",
          "bussiness_code = #{bussinessCode,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(BoxBusinessTemplateRelation record);

    int batchInsert(List<BoxBusinessTemplateRelation> list);

    int deleteByBusinessCode(String businessCode);
    
    Map<String,String> getBoxTemplate(String businessCode);
}