package com.cmiot.rms.dao.mapper;

import com.cmiot.rms.dao.model.BoxDiagnoseLog;
import org.apache.ibatis.annotations.*;

public interface BoxDiagnoseLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_box_diagnose_log
     *
     * @mbggenerated
     */
    @Delete({
        "delete from t_box_diagnose_log",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_box_diagnose_log
     *
     * @mbggenerated
     */
    @Insert({
        "insert into t_box_diagnose_log (id, box_macaddress, ",
        "diagnose_operator, diagnose_type, ",
        "diagnose_time)",
        "values (#{id,jdbcType=VARCHAR}, #{boxMacaddress,jdbcType=VARCHAR}, ",
        "#{diagnoseOperator,jdbcType=VARCHAR}, #{diagnoseType,jdbcType=INTEGER}, ",
        "#{diagnoseTime,jdbcType=TIMESTAMP})"
    })
    int insert(BoxDiagnoseLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_box_diagnose_log
     *
     * @mbggenerated
     */
    int insertSelective(BoxDiagnoseLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_box_diagnose_log
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, box_macaddress, diagnose_operator, diagnose_type, diagnose_time",
        "from t_box_diagnose_log",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    BoxDiagnoseLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_box_diagnose_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BoxDiagnoseLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_box_diagnose_log
     *
     * @mbggenerated
     */
    @Update({
        "update t_box_diagnose_log",
        "set box_macaddress = #{boxMacaddress,jdbcType=VARCHAR},",
          "diagnose_operator = #{diagnoseOperator,jdbcType=VARCHAR},",
          "diagnose_type = #{diagnoseType,jdbcType=INTEGER},",
          "diagnose_time = #{diagnoseTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(BoxDiagnoseLog record);
}