package com.cmiot.rms.dao.mapper;

import com.cmiot.rms.dao.model.BoxFactoryInfo;
import org.apache.ibatis.annotations.*;

import java.util.List;

public interface BoxFactoryInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_box_factory_info
     *
     * @mbggenerated
     */
    @Delete({
        "delete from t_box_factory_info",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_box_factory_info
     *
     * @mbggenerated
     */
    @Insert({
        "insert into t_box_factory_info (id, factory_code, ",
        "factory_name)",
        "values (#{id,jdbcType=VARCHAR}, #{factoryCode,jdbcType=CHAR}, ",
        "#{factoryName,jdbcType=CHAR})"
    })
    int insert(BoxFactoryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_box_factory_info
     *
     * @mbggenerated
     */
    int insertSelective(BoxFactoryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_box_factory_info
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, factory_code, factory_name",
        "from t_box_factory_info",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    BoxFactoryInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_box_factory_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BoxFactoryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_box_factory_info
     *
     * @mbggenerated
     */
    @Update({
        "update t_box_factory_info",
        "set factory_code = #{factoryCode,jdbcType=CHAR},",
          "factory_name = #{factoryName,jdbcType=CHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(BoxFactoryInfo record);

    List<BoxFactoryInfo> queryList(BoxFactoryInfo record);
}