package com.cmiot.rms.dao.mapper;

import com.cmiot.rms.dao.model.BoxFirmwarePrepared;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface BoxFirmwarePreparedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_box_firmware_prepared
     *
     * @mbggenerated
     */
    @Insert({
        "insert into t_box_firmware_prepared (firmware_id, firmware_previous_id, ",
        "need_force_upgrade)",
        "values (#{firmwareId,jdbcType=VARCHAR}, #{firmwarePreviousId,jdbcType=VARCHAR}, ",
        "#{needForceUpgrade,jdbcType=BIT})"
    })
    int insert(BoxFirmwarePrepared record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_box_firmware_prepared
     *
     * @mbggenerated
     */
    int insertSelective(BoxFirmwarePrepared record);

    /**
     * 查询固件的待升级固件信息
     * @param firmwareId
     * @return
     */
    List<Map<String, Object>> queryPreparedByFirmwareId(@Param("firmwareId") String firmwareId);

    List<BoxFirmwarePrepared> queryList(BoxFirmwarePrepared record);

    int deleteByFirmwareId(@Param("firmwareId") String firmwareId);
}