package com.cmiot.rms.dao.mapper;

import java.util.List;
import java.util.Map;

import com.cmiot.rms.dao.model.BoxFirmwareInfo;

import org.apache.ibatis.annotations.*;

public interface BoxFirmwareInfoMapper {
	
	List<BoxFirmwareInfo> selectByDeviceId();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_box_firmware_info
     *
     * @mbggenerated
     */
    @Delete({
        "delete from t_box_firmware_info",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_box_firmware_info
     *
     * @mbggenerated
     */
    @Insert({
        "insert into t_box_firmware_info (id, firmware_name, ",
        "firmware_version, firmware_path, ",
        "firmware_size, firmware_create_time, ",
        "firmware_description, factory_code, ",
        "box_type, box_model, device_id)",
        "values (#{id,jdbcType=VARCHAR}, #{firmwareName,jdbcType=VARCHAR}, ",
        "#{firmwareVersion,jdbcType=VARCHAR}, #{firmwarePath,jdbcType=CHAR}, ",
        "#{firmwareSize,jdbcType=DOUBLE}, #{firmwareCreateTime,jdbcType=INTEGER}, ",
        "#{firmwareDescription,jdbcType=VARCHAR}, #{factoryCode,jdbcType=VARCHAR}, ",
        "#{boxType,jdbcType=VARCHAR}, #{boxModel,jdbcType=VARCHAR}, #{deviceId,jdbcType=VARCHAR})"
    })
    int insert(BoxFirmwareInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_box_firmware_info
     *
     * @mbggenerated
     */
    int insertSelective(BoxFirmwareInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_box_firmware_info
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, firmware_name, firmware_version, firmware_path, firmware_size, firmware_create_time, ",
        "firmware_description, factory_code, box_type, box_model, device_id",
        "from t_box_firmware_info",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    BoxFirmwareInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_box_firmware_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BoxFirmwareInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_box_firmware_info
     *
     * @mbggenerated
     */
    @Update({
        "update t_box_firmware_info",
        "set firmware_name = #{firmwareName,jdbcType=VARCHAR},",
          "firmware_version = #{firmwareVersion,jdbcType=VARCHAR},",
          "firmware_path = #{firmwarePath,jdbcType=CHAR},",
          "firmware_size = #{firmwareSize,jdbcType=DOUBLE},",
          "firmware_create_time = #{firmwareCreateTime,jdbcType=INTEGER},",
          "firmware_description = #{firmwareDescription,jdbcType=VARCHAR},",
          "factory_code = #{factoryCode,jdbcType=VARCHAR},",
          "box_type = #{boxType,jdbcType=VARCHAR},",
          "box_model = #{boxModel,jdbcType=VARCHAR},",
          "device_id = #{deviceId,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(BoxFirmwareInfo record);

	List<BoxFirmwareInfo> queryFirmwareInfo(BoxFirmwareInfo firm);

    List<BoxFirmwareInfo> queryFirmware(BoxFirmwareInfo firm);

    /**
     * 查询固件数量
     * @param para
     * @return
     */
    int selectCount(Map<String, Object> para);
}