package com.cmiot.rms.dao.mapper;

import com.cmiot.rms.dao.model.BoxMetaParameter;
import org.apache.ibatis.annotations.*;

public interface BoxMetaParameterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_box_meta_parameter
     *
     * @mbggenerated
     */
    @Delete({
        "delete from t_box_meta_parameter",
        "where parm_id = #{parmId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer parmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_box_meta_parameter
     *
     * @mbggenerated
     */
    @Insert({
        "insert into t_box_meta_parameter (parm_id, parm_name, ",
        "parm_type, parm_length, ",
        "parm_writeable, parm_value, ",
        "parm_factory)",
        "values (#{parmId,jdbcType=INTEGER}, #{parmName,jdbcType=VARCHAR}, ",
        "#{parmType,jdbcType=VARCHAR}, #{parmLength,jdbcType=INTEGER}, ",
        "#{parmWriteable,jdbcType=VARCHAR}, #{parmValue,jdbcType=VARCHAR}, ",
        "#{parmFactory,jdbcType=VARCHAR})"
    })
    int insert(BoxMetaParameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_box_meta_parameter
     *
     * @mbggenerated
     */
    int insertSelective(BoxMetaParameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_box_meta_parameter
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "parm_id, parm_name, parm_type, parm_length, parm_writeable, parm_value, parm_factory",
        "from t_box_meta_parameter",
        "where parm_id = #{parmId,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    BoxMetaParameter selectByPrimaryKey(Integer parmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_box_meta_parameter
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BoxMetaParameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_box_meta_parameter
     *
     * @mbggenerated
     */
    @Update({
        "update t_box_meta_parameter",
        "set parm_name = #{parmName,jdbcType=VARCHAR},",
          "parm_type = #{parmType,jdbcType=VARCHAR},",
          "parm_length = #{parmLength,jdbcType=INTEGER},",
          "parm_writeable = #{parmWriteable,jdbcType=VARCHAR},",
          "parm_value = #{parmValue,jdbcType=VARCHAR},",
          "parm_factory = #{parmFactory,jdbcType=VARCHAR}",
        "where parm_id = #{parmId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(BoxMetaParameter record);
}