package com.cmiot.rms.dao.mapper;

import com.cmiot.rms.dao.model.BusinessTemplateRelation;
import org.apache.ibatis.annotations.*;

import java.util.List;

public interface BusinessTemplateRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business_template_relation
     *
     * @mbggenerated
     */
    @Delete({
        "delete from t_business_template_relation",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business_template_relation
     *
     * @mbggenerated
     */
    @Insert({
        "insert into t_business_template_relation (id, manufacturerID, ",
        "manufacturer_name, factoryID, ",
        "factory_name, gateway_model, ",
        "hd_version, firmware_version, ",
        "business_template, bussiness_code)",
        "values (#{id,jdbcType=VARCHAR}, #{manufacturerid,jdbcType=VARCHAR}, ",
        "#{manufacturerName,jdbcType=VARCHAR}, #{factoryid,jdbcType=VARCHAR}, ",
        "#{factoryName,jdbcType=VARCHAR}, #{gatewayModel,jdbcType=VARCHAR}, ",
        "#{hdVersion,jdbcType=VARCHAR}, #{firmwareVersion,jdbcType=VARCHAR}, ",
        "#{businessTemplate,jdbcType=VARCHAR}, #{bussinessCode,jdbcType=VARCHAR})"
    })
    int insert(BusinessTemplateRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business_template_relation
     *
     * @mbggenerated
     */
    int insertSelective(BusinessTemplateRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business_template_relation
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, manufacturerID, manufacturer_name, factoryID, factory_name, gateway_model, ",
        "hd_version, firmware_version, business_template, bussiness_code",
        "from t_business_template_relation",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    BusinessTemplateRelation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business_template_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BusinessTemplateRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business_template_relation
     *
     * @mbggenerated
     */
    @Update({
        "update t_business_template_relation",
        "set manufacturerID = #{manufacturerid,jdbcType=VARCHAR},",
          "manufacturer_name = #{manufacturerName,jdbcType=VARCHAR},",
          "factoryID = #{factoryid,jdbcType=VARCHAR},",
          "factory_name = #{factoryName,jdbcType=VARCHAR},",
          "gateway_model = #{gatewayModel,jdbcType=VARCHAR},",
          "hd_version = #{hdVersion,jdbcType=VARCHAR},",
          "firmware_version = #{firmwareVersion,jdbcType=VARCHAR},",
          "business_template = #{businessTemplate,jdbcType=VARCHAR},",
          "bussiness_code = #{bussinessCode,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(BusinessTemplateRelation record);

    int batchInsert(List<BusinessTemplateRelation> list);

    int deleteByBusinessCode(String businessCode);
}