package com.cmiot.rms.dao.mapper;

import com.cmiot.rms.dao.model.GatewayBusinessOpenDetail;

import org.apache.ibatis.annotations.*;

import java.util.List;
import java.util.Map;

public interface GatewayBusinessOpenDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gateway_business_open_detail
     *
     * @mbggenerated
     */
    @Delete({
        "delete from t_gateway_business_open_detail",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gateway_business_open_detail
     *
     * @mbggenerated
     */
    @Insert({
        "insert into t_gateway_business_open_detail (id, business_code_boss, ",
        "gateway_uuid, open_status, ",
        "order_no)",
        "values (#{id,jdbcType=VARCHAR}, #{businessCodeBoss,jdbcType=VARCHAR}, ",
        "#{gatewayUuid,jdbcType=VARCHAR}, #{openStatus,jdbcType=VARCHAR}, ",
        "#{orderNo,jdbcType=VARCHAR})"
    })
    int insert(GatewayBusinessOpenDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gateway_business_open_detail
     *
     * @mbggenerated
     */
    int insertSelective(GatewayBusinessOpenDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gateway_business_open_detail
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, business_code_boss, gateway_uuid, open_status, order_no",
        "from t_gateway_business_open_detail",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    GatewayBusinessOpenDetail selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gateway_business_open_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GatewayBusinessOpenDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gateway_business_open_detail
     *
     * @mbggenerated
     */
    @Update({
        "update t_gateway_business_open_detail",
        "set business_code_boss = #{businessCodeBoss,jdbcType=VARCHAR},",
          "gateway_uuid = #{gatewayUuid,jdbcType=VARCHAR},",
          "open_status = #{openStatus,jdbcType=VARCHAR},",
          "order_no = #{orderNo,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(GatewayBusinessOpenDetail record);

    GatewayBusinessOpenDetail selectByParam(GatewayBusinessOpenDetail gatewayBusinessOpenDetail);

    List<Map<String,Object>> selectByGatewayUuid(String gatewayUuid);

    int updateByGatewayUuid(GatewayBusinessOpenDetail record);

    @Delete({
        "delete from t_gateway_business_open_detail",
        "where gateway_uuid = #{gatewayUuid,jdbcType=VARCHAR}"
    })
    int deleteByGatewayId(String gatewayUuid);

    String selectBusinessOpen(Map map);

	void updateOpenStatusByGatewayUuid(Map<String, Object> parm);
}