package com.cmiot.rms.dao.mapper;

import com.cmiot.rms.dao.model.GatewayPassword;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface GatewayPasswordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gateway_password
     *
     * @mbggenerated
     */
    @Delete({
        "delete from t_gateway_password",
        "where gateway_password = #{gatewayPassword,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String gatewayPassword);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gateway_password
     *
     * @mbggenerated
     */
    @Insert({
        "insert into t_gateway_password (gateway_password, order_no,adsl_account)",
        "values (#{gatewayPassword,jdbcType=VARCHAR}, #{orderNo,jdbcType=VARCHAR}, #{adslAccount,jdbcType=VARCHAR})"
    })
    int insert(GatewayPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gateway_password
     *
     * @mbggenerated
     */
    int insertSelective(GatewayPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gateway_password
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "gateway_password, order_no, adsl_account",
        "from t_gateway_password",
        "where gateway_password = #{gatewayPassword,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    GatewayPassword selectByPrimaryKey(String gatewayPassword);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gateway_password
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GatewayPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gateway_password
     *
     * @mbggenerated
     */
    @Update({
        "update t_gateway_password",
        "set order_no = #{orderNo,jdbcType=VARCHAR},adsl_account = #{adslAccount,jdbcType=VARCHAR}",
        "where gateway_password = #{gatewayPassword,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(GatewayPassword record);

    GatewayPassword selectByPassword(GatewayPassword gatewayPassword);


    GatewayPassword selectBySelective(GatewayPassword gatewayPassword);


    @Delete({
        "delete from t_gateway_password",
        "where order_no = #{orderNo,jdbcType=VARCHAR}"
    })
    int deleteByOrderNo(String orderNo);

    @Delete({
        "delete from t_gateway_password",
        "where adsl_account = #{adslAccount,jdbcType=VARCHAR}"
    })
    int deleteByAdslNo(String adslAccount);
}