package com.cmiot.rms.dao.mapper;

import com.cmiot.rms.dao.model.HdVersionInfo;
import org.apache.ibatis.annotations.*;

import java.util.List;
import java.util.Map;

public interface HdVersionInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hd_version_info
     *
     * @mbggenerated
     */
    @Delete({
        "delete from t_hd_version_info",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hd_version_info
     *
     * @mbggenerated
     */
    @Insert({
        "insert into t_hd_version_info (id, hd_version, ",
        "device_model, device_id, ",
        "create_time)",
        "values (#{id,jdbcType=VARCHAR}, #{hdVersion,jdbcType=VARCHAR}, ",
        "#{deviceModel,jdbcType=VARCHAR}, #{deviceId,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=VARCHAR})"
    })
    int insert(HdVersionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hd_version_info
     *
     * @mbggenerated
     */
    int insertSelective(HdVersionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hd_version_info
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, hd_version, device_model, device_id, create_time",
        "from t_hd_version_info",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    HdVersionInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hd_version_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HdVersionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hd_version_info
     *
     * @mbggenerated
     */
    @Update({
        "update t_hd_version_info",
        "set hd_version = #{hdVersion,jdbcType=VARCHAR},",
          "device_model = #{deviceModel,jdbcType=VARCHAR},",
          "device_id = #{deviceId,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=VARCHAR},",
            "description = #{description,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(HdVersionInfo record);

    List<HdVersionInfo> queryByParam(HdVersionInfo record);

    List<Map<String,Object>> queryList4Page(Map<String,Object> map);
}