package com.cmiot.rms.dao.model;

public class BoxBusinessExecuteHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gateway_business_execute_history.order_no
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gateway_business_execute_history.execute_time
     *
     * @mbggenerated
     */
    private Integer executeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gateway_business_execute_history.execute_status
     *
     * @mbggenerated
     */
    private Integer executeStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gateway_business_execute_history.order_no
     *
     * @return the value of t_gateway_business_execute_history.order_no
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gateway_business_execute_history.order_no
     *
     * @param orderNo the value for t_gateway_business_execute_history.order_no
     *
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gateway_business_execute_history.execute_time
     *
     * @return the value of t_gateway_business_execute_history.execute_time
     *
     * @mbggenerated
     */
    public Integer getExecuteTime() {
        return executeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gateway_business_execute_history.execute_time
     *
     * @param executeTime the value for t_gateway_business_execute_history.execute_time
     *
     * @mbggenerated
     */
    public void setExecuteTime(Integer executeTime) {
        this.executeTime = executeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gateway_business_execute_history.execute_status
     *
     * @return the value of t_gateway_business_execute_history.execute_status
     *
     * @mbggenerated
     */
    public Integer getExecuteStatus() {
        return executeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gateway_business_execute_history.execute_status
     *
     * @param executeStatus the value for t_gateway_business_execute_history.execute_status
     *
     * @mbggenerated
     */
    public void setExecuteStatus(Integer executeStatus) {
        this.executeStatus = executeStatus;
    }
}