package com.cmiot.rms.dao.model;

public class BoxFirmwarePrepared {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_firmware_prepared.firmware_id
     *
     * @mbggenerated
     */
    private String firmwareId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_firmware_prepared.firmware_previous_id
     *
     * @mbggenerated
     */
    private String firmwarePreviousId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_firmware_prepared.need_force_upgrade
     *
     * @mbggenerated
     */
    private Boolean needForceUpgrade;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_firmware_prepared.firmware_id
     *
     * @return the value of t_box_firmware_prepared.firmware_id
     *
     * @mbggenerated
     */
    public String getFirmwareId() {
        return firmwareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_firmware_prepared.firmware_id
     *
     * @param firmwareId the value for t_box_firmware_prepared.firmware_id
     *
     * @mbggenerated
     */
    public void setFirmwareId(String firmwareId) {
        this.firmwareId = firmwareId == null ? null : firmwareId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_firmware_prepared.firmware_previous_id
     *
     * @return the value of t_box_firmware_prepared.firmware_previous_id
     *
     * @mbggenerated
     */
    public String getFirmwarePreviousId() {
        return firmwarePreviousId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_firmware_prepared.firmware_previous_id
     *
     * @param firmwarePreviousId the value for t_box_firmware_prepared.firmware_previous_id
     *
     * @mbggenerated
     */
    public void setFirmwarePreviousId(String firmwarePreviousId) {
        this.firmwarePreviousId = firmwarePreviousId == null ? null : firmwarePreviousId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_firmware_prepared.need_force_upgrade
     *
     * @return the value of t_box_firmware_prepared.need_force_upgrade
     *
     * @mbggenerated
     */
    public Boolean getNeedForceUpgrade() {
        return needForceUpgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_firmware_prepared.need_force_upgrade
     *
     * @param needForceUpgrade the value for t_box_firmware_prepared.need_force_upgrade
     *
     * @mbggenerated
     */
    public void setNeedForceUpgrade(Boolean needForceUpgrade) {
        this.needForceUpgrade = needForceUpgrade;
    }
}