package com.cmiot.rms.dao.model;

public class BoxFactoryInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_factory_info.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_factory_info.factory_code
     *
     * @mbggenerated
     */
    private String factoryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_factory_info.factory_name
     *
     * @mbggenerated
     */
    private String factoryName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_factory_info.id
     *
     * @return the value of t_box_factory_info.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_factory_info.id
     *
     * @param id the value for t_box_factory_info.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_factory_info.factory_code
     *
     * @return the value of t_box_factory_info.factory_code
     *
     * @mbggenerated
     */
    public String getFactoryCode() {
        return factoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_factory_info.factory_code
     *
     * @param factoryCode the value for t_box_factory_info.factory_code
     *
     * @mbggenerated
     */
    public void setFactoryCode(String factoryCode) {
        this.factoryCode = factoryCode == null ? null : factoryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_factory_info.factory_name
     *
     * @return the value of t_box_factory_info.factory_name
     *
     * @mbggenerated
     */
    public String getFactoryName() {
        return factoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_factory_info.factory_name
     *
     * @param factoryName the value for t_box_factory_info.factory_name
     *
     * @mbggenerated
     */
    public void setFactoryName(String factoryName) {
        this.factoryName = factoryName == null ? null : factoryName.trim();
    }
}