package com.cmiot.rms.dao.model;

import java.util.List;
import java.util.Map;

public class BoxFirmwareInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_firmware_info.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_firmware_info.firmware_name
     *
     * @mbggenerated
     */
    private String firmwareName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_firmware_info.firmware_version
     *
     * @mbggenerated
     */
    private String firmwareVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_firmware_info.firmware_path
     *
     * @mbggenerated
     */
    private String firmwarePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_firmware_info.firmware_size
     *
     * @mbggenerated
     */
    private Double firmwareSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_firmware_info.firmware_create_time
     *
     * @mbggenerated
     */
    private Integer firmwareCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_firmware_info.firmware_description
     *
     * @mbggenerated
     */
    private String firmwareDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_firmware_info.factory_code
     *
     * @mbggenerated
     */
    private String factoryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_firmware_info.box_type
     *
     * @mbggenerated
     */
    private String boxType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_firmware_info.box_model
     *
     * @mbggenerated
     */
    private String boxModel;


    /**
     * 待升级固件列表
     */
    private List<Map<String, Object>> prepared;



    private String factoryName;
    
    private String deviceId;//设备UUID
    
    

    public String getDeviceId() {
		return deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_firmware_info.id
     *
     * @return the value of t_box_firmware_info.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_firmware_info.id
     *
     * @param id the value for t_box_firmware_info.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_firmware_info.firmware_name
     *
     * @return the value of t_box_firmware_info.firmware_name
     *
     * @mbggenerated
     */
    public String getFirmwareName() {
        return firmwareName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_firmware_info.firmware_name
     *
     * @param firmwareName the value for t_box_firmware_info.firmware_name
     *
     * @mbggenerated
     */
    public void setFirmwareName(String firmwareName) {
        this.firmwareName = firmwareName == null ? null : firmwareName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_firmware_info.firmware_version
     *
     * @return the value of t_box_firmware_info.firmware_version
     *
     * @mbggenerated
     */
    public String getFirmwareVersion() {
        return firmwareVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_firmware_info.firmware_version
     *
     * @param firmwareVersion the value for t_box_firmware_info.firmware_version
     *
     * @mbggenerated
     */
    public void setFirmwareVersion(String firmwareVersion) {
        this.firmwareVersion = firmwareVersion == null ? null : firmwareVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_firmware_info.firmware_path
     *
     * @return the value of t_box_firmware_info.firmware_path
     *
     * @mbggenerated
     */
    public String getFirmwarePath() {
        return firmwarePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_firmware_info.firmware_path
     *
     * @param firmwarePath the value for t_box_firmware_info.firmware_path
     *
     * @mbggenerated
     */
    public void setFirmwarePath(String firmwarePath) {
        this.firmwarePath = firmwarePath == null ? null : firmwarePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_firmware_info.firmware_size
     *
     * @return the value of t_box_firmware_info.firmware_size
     *
     * @mbggenerated
     */
    public Double getFirmwareSize() {
        return firmwareSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_firmware_info.firmware_size
     *
     * @param firmwareSize the value for t_box_firmware_info.firmware_size
     *
     * @mbggenerated
     */
    public void setFirmwareSize(Double firmwareSize) {
        this.firmwareSize = firmwareSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_firmware_info.firmware_create_time
     *
     * @return the value of t_box_firmware_info.firmware_create_time
     *
     * @mbggenerated
     */
    public Integer getFirmwareCreateTime() {
        return firmwareCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_firmware_info.firmware_create_time
     *
     * @param firmwareCreateTime the value for t_box_firmware_info.firmware_create_time
     *
     * @mbggenerated
     */
    public void setFirmwareCreateTime(Integer firmwareCreateTime) {
        this.firmwareCreateTime = firmwareCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_firmware_info.firmware_description
     *
     * @return the value of t_box_firmware_info.firmware_description
     *
     * @mbggenerated
     */
    public String getFirmwareDescription() {
        return firmwareDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_firmware_info.firmware_description
     *
     * @param firmwareDescription the value for t_box_firmware_info.firmware_description
     *
     * @mbggenerated
     */
    public void setFirmwareDescription(String firmwareDescription) {
        this.firmwareDescription = firmwareDescription == null ? null : firmwareDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_firmware_info.factory_code
     *
     * @return the value of t_box_firmware_info.factory_code
     *
     * @mbggenerated
     */
    public String getFactoryCode() {
        return factoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_firmware_info.factory_code
     *
     * @param factoryCode the value for t_box_firmware_info.factory_code
     *
     * @mbggenerated
     */
    public void setFactoryCode(String factoryCode) {
        this.factoryCode = factoryCode == null ? null : factoryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_firmware_info.box_type
     *
     * @return the value of t_box_firmware_info.box_type
     *
     * @mbggenerated
     */
    public String getBoxType() {
        return boxType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_firmware_info.box_type
     *
     * @param boxType the value for t_box_firmware_info.box_type
     *
     * @mbggenerated
     */
    public void setBoxType(String boxType) {
        this.boxType = boxType == null ? null : boxType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_firmware_info.box_model
     *
     * @return the value of t_box_firmware_info.box_model
     *
     * @mbggenerated
     */
    public String getBoxModel() {
        return boxModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_firmware_info.box_model
     *
     * @param boxModel the value for t_box_firmware_info.box_model
     *
     * @mbggenerated
     */
    public void setBoxModel(String boxModel) {
        this.boxModel = boxModel == null ? null : boxModel.trim();
    }

    public List<Map<String, Object>> getPrepared() {
        return prepared;
    }

    public void setPrepared(List<Map<String, Object>> prepared) {
        this.prepared = prepared;
    }

    public String getFactoryName() {
        return factoryName;
    }

    public void setFactoryName(String factoryName) {
        this.factoryName = factoryName;
    }
}