package com.cmiot.rms.dao.model;

import java.io.Serializable;

public class BoxInfo implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_info.box_uuid
     *
     * @mbggenerated
     */
    private String boxUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_info.box_name
     *
     * @mbggenerated
     */
    private String boxName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_info.box_serialnumber
     *
     * @mbggenerated
     */
    private String boxSerialnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_info.box_macaddress
     *
     * @mbggenerated
     */
    private String boxMacaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_info.gateway_uuid
     *
     * @mbggenerated
     */
    private String gatewayUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_info.box_type
     *
     * @mbggenerated
     */
    private String boxType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_info.box_model
     *
     * @mbggenerated
     */
    private String boxModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_info.box_factory_code
     *
     * @mbggenerated
     */
    private String boxFactoryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_info.box_online
     *
     * @mbggenerated
     */
    private Integer boxOnline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_info.box_firmware_uuid
     *
     * @mbggenerated
     */
    private String boxFirmwareUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_info.box_hardware_version
     *
     * @mbggenerated
     */
    private String boxHardwareVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_info.box_area_id
     *
     * @mbggenerated
     */
    private String boxAreaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_info.box_memo
     *
     * @mbggenerated
     */
    private String boxMemo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_info.box_ipaddress
     *
     * @mbggenerated
     */
    private String boxIpaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_info.box_url
     *
     * @mbggenerated
     */
    private String boxUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_info.box_connectionrequesturl
     *
     * @mbggenerated
     */
    private String boxConnectionrequesturl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_info.box_conn_type
     *
     * @mbggenerated
     */
    private String boxConnType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_info.box_digest_account
     *
     * @mbggenerated
     */
    private String boxDigestAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_info.box_digest_password
     *
     * @mbggenerated
     */
    private String boxDigestPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_info.box_family_account
     *
     * @mbggenerated
     */
    private String boxFamilyAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_info.box_family_password
     *
     * @mbggenerated
     */
    private String boxFamilyPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_info.box_file_url
     *
     * @mbggenerated
     */
    private String boxFileUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_info.box_join_time
     *
     * @mbggenerated
     */
    private Integer boxJoinTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_info.box_last_conn_time
     *
     * @mbggenerated
     */
    private Integer boxLastConnTime;

    private String boxStatus;
    
    private String boxConnectAccount;
    
    private String boxConnectPassword;

    /**
     * 机顶盒厂商名称，冗余字段
     */
    private String boxFactoryName;

    public String getBoxFactoryName() {
        return boxFactoryName;
    }

    public void setBoxFactoryName(String boxFactoryName) {
        this.boxFactoryName = boxFactoryName;
    }

    public String getBoxStatus() {
        return boxStatus;
    }

    public void setBoxStatus(String boxStatus) {
        this.boxStatus = boxStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_info.box_uuid
     *
     * @return the value of t_box_info.box_uuid
     *
     * @mbggenerated
     */
    public String getBoxUuid() {
        return boxUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_info.box_uuid
     *
     * @param boxUuid the value for t_box_info.box_uuid
     *
     * @mbggenerated
     */
    public void setBoxUuid(String boxUuid) {
        this.boxUuid = boxUuid == null ? null : boxUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_info.box_name
     *
     * @return the value of t_box_info.box_name
     *
     * @mbggenerated
     */
    public String getBoxName() {
        return boxName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_info.box_name
     *
     * @param boxName the value for t_box_info.box_name
     *
     * @mbggenerated
     */
    public void setBoxName(String boxName) {
        this.boxName = boxName == null ? null : boxName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_info.box_serialnumber
     *
     * @return the value of t_box_info.box_serialnumber
     *
     * @mbggenerated
     */
    public String getBoxSerialnumber() {
        return boxSerialnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_info.box_serialnumber
     *
     * @param boxSerialnumber the value for t_box_info.box_serialnumber
     *
     * @mbggenerated
     */
    public void setBoxSerialnumber(String boxSerialnumber) {
        this.boxSerialnumber = boxSerialnumber == null ? null : boxSerialnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_info.box_macaddress
     *
     * @return the value of t_box_info.box_macaddress
     *
     * @mbggenerated
     */
    public String getBoxMacaddress() {
        return boxMacaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_info.box_macaddress
     *
     * @param boxMacaddress the value for t_box_info.box_macaddress
     *
     * @mbggenerated
     */
    public void setBoxMacaddress(String boxMacaddress) {
        this.boxMacaddress = boxMacaddress == null ? null : boxMacaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_info.gateway_uuid
     *
     * @return the value of t_box_info.gateway_uuid
     *
     * @mbggenerated
     */
    public String getGatewayUuid() {
        return gatewayUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_info.gateway_uuid
     *
     * @param gatewayUuid the value for t_box_info.gateway_uuid
     *
     * @mbggenerated
     */
    public void setGatewayUuid(String gatewayUuid) {
        this.gatewayUuid = gatewayUuid == null ? null : gatewayUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_info.box_type
     *
     * @return the value of t_box_info.box_type
     *
     * @mbggenerated
     */
    public String getBoxType() {
        return boxType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_info.box_type
     *
     * @param boxType the value for t_box_info.box_type
     *
     * @mbggenerated
     */
    public void setBoxType(String boxType) {
        this.boxType = boxType == null ? null : boxType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_info.box_model
     *
     * @return the value of t_box_info.box_model
     *
     * @mbggenerated
     */
    public String getBoxModel() {
        return boxModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_info.box_model
     *
     * @param boxModel the value for t_box_info.box_model
     *
     * @mbggenerated
     */
    public void setBoxModel(String boxModel) {
        this.boxModel = boxModel == null ? null : boxModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_info.box_factory_code
     *
     * @return the value of t_box_info.box_factory_code
     *
     * @mbggenerated
     */
    public String getBoxFactoryCode() {
        return boxFactoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_info.box_factory_code
     *
     * @param boxFactoryCode the value for t_box_info.box_factory_code
     *
     * @mbggenerated
     */
    public void setBoxFactoryCode(String boxFactoryCode) {
        this.boxFactoryCode = boxFactoryCode == null ? null : boxFactoryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_info.box_online
     *
     * @return the value of t_box_info.box_online
     *
     * @mbggenerated
     */
    public Integer getBoxOnline() {
        return boxOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_info.box_online
     *
     * @param boxOnline the value for t_box_info.box_online
     *
     * @mbggenerated
     */
    public void setBoxOnline(Integer boxOnline) {
        this.boxOnline = boxOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_info.box_firmware_uuid
     *
     * @return the value of t_box_info.box_firmware_uuid
     *
     * @mbggenerated
     */
    public String getBoxFirmwareUuid() {
        return boxFirmwareUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_info.box_firmware_uuid
     *
     * @param boxFirmwareUuid the value for t_box_info.box_firmware_uuid
     *
     * @mbggenerated
     */
    public void setBoxFirmwareUuid(String boxFirmwareUuid) {
        this.boxFirmwareUuid = boxFirmwareUuid == null ? null : boxFirmwareUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_info.box_hardware_version
     *
     * @return the value of t_box_info.box_hardware_version
     *
     * @mbggenerated
     */
    public String getBoxHardwareVersion() {
        return boxHardwareVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_info.box_hardware_version
     *
     * @param boxHardwareVersion the value for t_box_info.box_hardware_version
     *
     * @mbggenerated
     */
    public void setBoxHardwareVersion(String boxHardwareVersion) {
        this.boxHardwareVersion = boxHardwareVersion == null ? null : boxHardwareVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_info.box_area_id
     *
     * @return the value of t_box_info.box_area_id
     *
     * @mbggenerated
     */
    public String getBoxAreaId() {
        return boxAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_info.box_area_id
     *
     * @param boxAreaId the value for t_box_info.box_area_id
     *
     * @mbggenerated
     */
    public void setBoxAreaId(String boxAreaId) {
        this.boxAreaId = boxAreaId == null ? null : boxAreaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_info.box_memo
     *
     * @return the value of t_box_info.box_memo
     *
     * @mbggenerated
     */
    public String getBoxMemo() {
        return boxMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_info.box_memo
     *
     * @param boxMemo the value for t_box_info.box_memo
     *
     * @mbggenerated
     */
    public void setBoxMemo(String boxMemo) {
        this.boxMemo = boxMemo == null ? null : boxMemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_info.box_ipaddress
     *
     * @return the value of t_box_info.box_ipaddress
     *
     * @mbggenerated
     */
    public String getBoxIpaddress() {
        return boxIpaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_info.box_ipaddress
     *
     * @param boxIpaddress the value for t_box_info.box_ipaddress
     *
     * @mbggenerated
     */
    public void setBoxIpaddress(String boxIpaddress) {
        this.boxIpaddress = boxIpaddress == null ? null : boxIpaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_info.box_url
     *
     * @return the value of t_box_info.box_url
     *
     * @mbggenerated
     */
    public String getBoxUrl() {
        return boxUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_info.box_url
     *
     * @param boxUrl the value for t_box_info.box_url
     *
     * @mbggenerated
     */
    public void setBoxUrl(String boxUrl) {
        this.boxUrl = boxUrl == null ? null : boxUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_info.box_connectionrequesturl
     *
     * @return the value of t_box_info.box_connectionrequesturl
     *
     * @mbggenerated
     */
    public String getBoxConnectionrequesturl() {
        return boxConnectionrequesturl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_info.box_connectionrequesturl
     *
     * @param boxConnectionrequesturl the value for t_box_info.box_connectionrequesturl
     *
     * @mbggenerated
     */
    public void setBoxConnectionrequesturl(String boxConnectionrequesturl) {
        this.boxConnectionrequesturl = boxConnectionrequesturl == null ? null : boxConnectionrequesturl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_info.box_conn_type
     *
     * @return the value of t_box_info.box_conn_type
     *
     * @mbggenerated
     */
    public String getBoxConnType() {
        return boxConnType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_info.box_conn_type
     *
     * @param boxConnType the value for t_box_info.box_conn_type
     *
     * @mbggenerated
     */
    public void setBoxConnType(String boxConnType) {
        this.boxConnType = boxConnType == null ? null : boxConnType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_info.box_digest_account
     *
     * @return the value of t_box_info.box_digest_account
     *
     * @mbggenerated
     */
    public String getBoxDigestAccount() {
        return boxDigestAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_info.box_digest_account
     *
     * @param boxDigestAccount the value for t_box_info.box_digest_account
     *
     * @mbggenerated
     */
    public void setBoxDigestAccount(String boxDigestAccount) {
        this.boxDigestAccount = boxDigestAccount == null ? null : boxDigestAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_info.box_digest_password
     *
     * @return the value of t_box_info.box_digest_password
     *
     * @mbggenerated
     */
    public String getBoxDigestPassword() {
        return boxDigestPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_info.box_digest_password
     *
     * @param boxDigestPassword the value for t_box_info.box_digest_password
     *
     * @mbggenerated
     */
    public void setBoxDigestPassword(String boxDigestPassword) {
        this.boxDigestPassword = boxDigestPassword == null ? null : boxDigestPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_info.box_family_account
     *
     * @return the value of t_box_info.box_family_account
     *
     * @mbggenerated
     */
    public String getBoxFamilyAccount() {
        return boxFamilyAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_info.box_family_account
     *
     * @param boxFamilyAccount the value for t_box_info.box_family_account
     *
     * @mbggenerated
     */
    public void setBoxFamilyAccount(String boxFamilyAccount) {
        this.boxFamilyAccount = boxFamilyAccount == null ? null : boxFamilyAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_info.box_family_password
     *
     * @return the value of t_box_info.box_family_password
     *
     * @mbggenerated
     */
    public String getBoxFamilyPassword() {
        return boxFamilyPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_info.box_family_password
     *
     * @param boxFamilyPassword the value for t_box_info.box_family_password
     *
     * @mbggenerated
     */
    public void setBoxFamilyPassword(String boxFamilyPassword) {
        this.boxFamilyPassword = boxFamilyPassword == null ? null : boxFamilyPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_info.box_file_url
     *
     * @return the value of t_box_info.box_file_url
     *
     * @mbggenerated
     */
    public String getBoxFileUrl() {
        return boxFileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_info.box_file_url
     *
     * @param boxFileUrl the value for t_box_info.box_file_url
     *
     * @mbggenerated
     */
    public void setBoxFileUrl(String boxFileUrl) {
        this.boxFileUrl = boxFileUrl == null ? null : boxFileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_info.box_join_time
     *
     * @return the value of t_box_info.box_join_time
     *
     * @mbggenerated
     */
    public Integer getBoxJoinTime() {
        return boxJoinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_info.box_join_time
     *
     * @param boxJoinTime the value for t_box_info.box_join_time
     *
     * @mbggenerated
     */
    public void setBoxJoinTime(Integer boxJoinTime) {
        this.boxJoinTime = boxJoinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_info.box_last_conn_time
     *
     * @return the value of t_box_info.box_last_conn_time
     *
     * @mbggenerated
     */
    public Integer getBoxLastConnTime() {
        return boxLastConnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_info.box_last_conn_time
     *
     * @param boxLastConnTime the value for t_box_info.box_last_conn_time
     *
     * @mbggenerated
     */
    public void setBoxLastConnTime(Integer boxLastConnTime) {
        this.boxLastConnTime = boxLastConnTime;
    }

	public String getBoxConnectAccount() {
		return boxConnectAccount;
	}

	public void setBoxConnectAccount(String boxConnectAccount) {
		this.boxConnectAccount = boxConnectAccount;
	}

	public String getBoxConnectPassword() {
		return boxConnectPassword;
	}

	public void setBoxConnectPassword(String boxConnectPassword) {
		this.boxConnectPassword = boxConnectPassword;
	}
    
    
}