package com.cmiot.rms.dao.model;

public class BoxMetaParameter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_meta_parameter.parm_id
     *
     * @mbggenerated
     */
    private Integer parmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_meta_parameter.parm_name
     *
     * @mbggenerated
     */
    private String parmName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_meta_parameter.parm_type
     *
     * @mbggenerated
     */
    private String parmType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_meta_parameter.parm_length
     *
     * @mbggenerated
     */
    private Integer parmLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_meta_parameter.parm_writeable
     *
     * @mbggenerated
     */
    private String parmWriteable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_meta_parameter.parm_value
     *
     * @mbggenerated
     */
    private String parmValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_box_meta_parameter.parm_factory
     *
     * @mbggenerated
     */
    private String parmFactory;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_meta_parameter.parm_id
     *
     * @return the value of t_box_meta_parameter.parm_id
     *
     * @mbggenerated
     */
    public Integer getParmId() {
        return parmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_meta_parameter.parm_id
     *
     * @param parmId the value for t_box_meta_parameter.parm_id
     *
     * @mbggenerated
     */
    public void setParmId(Integer parmId) {
        this.parmId = parmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_meta_parameter.parm_name
     *
     * @return the value of t_box_meta_parameter.parm_name
     *
     * @mbggenerated
     */
    public String getParmName() {
        return parmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_meta_parameter.parm_name
     *
     * @param parmName the value for t_box_meta_parameter.parm_name
     *
     * @mbggenerated
     */
    public void setParmName(String parmName) {
        this.parmName = parmName == null ? null : parmName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_meta_parameter.parm_type
     *
     * @return the value of t_box_meta_parameter.parm_type
     *
     * @mbggenerated
     */
    public String getParmType() {
        return parmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_meta_parameter.parm_type
     *
     * @param parmType the value for t_box_meta_parameter.parm_type
     *
     * @mbggenerated
     */
    public void setParmType(String parmType) {
        this.parmType = parmType == null ? null : parmType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_meta_parameter.parm_length
     *
     * @return the value of t_box_meta_parameter.parm_length
     *
     * @mbggenerated
     */
    public Integer getParmLength() {
        return parmLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_meta_parameter.parm_length
     *
     * @param parmLength the value for t_box_meta_parameter.parm_length
     *
     * @mbggenerated
     */
    public void setParmLength(Integer parmLength) {
        this.parmLength = parmLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_meta_parameter.parm_writeable
     *
     * @return the value of t_box_meta_parameter.parm_writeable
     *
     * @mbggenerated
     */
    public String getParmWriteable() {
        return parmWriteable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_meta_parameter.parm_writeable
     *
     * @param parmWriteable the value for t_box_meta_parameter.parm_writeable
     *
     * @mbggenerated
     */
    public void setParmWriteable(String parmWriteable) {
        this.parmWriteable = parmWriteable == null ? null : parmWriteable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_meta_parameter.parm_value
     *
     * @return the value of t_box_meta_parameter.parm_value
     *
     * @mbggenerated
     */
    public String getParmValue() {
        return parmValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_meta_parameter.parm_value
     *
     * @param parmValue the value for t_box_meta_parameter.parm_value
     *
     * @mbggenerated
     */
    public void setParmValue(String parmValue) {
        this.parmValue = parmValue == null ? null : parmValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_box_meta_parameter.parm_factory
     *
     * @return the value of t_box_meta_parameter.parm_factory
     *
     * @mbggenerated
     */
    public String getParmFactory() {
        return parmFactory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_box_meta_parameter.parm_factory
     *
     * @param parmFactory the value for t_box_meta_parameter.parm_factory
     *
     * @mbggenerated
     */
    public void setParmFactory(String parmFactory) {
        this.parmFactory = parmFactory == null ? null : parmFactory.trim();
    }
}