package com.cmiot.rms.dao.model;

import java.io.Serializable;

public class BoxWorkOrderTemplateInfo implements Serializable {
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_work_order_template_info.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_work_order_template_info.template_name
     *
     * @mbggenerated
     */
    private String templateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_work_order_template_info.template_message
     *
     * @mbggenerated
     */
    private String templateMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_work_order_template_info.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_work_order_template_info.id
     *
     * @return the value of t_work_order_template_info.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_work_order_template_info.id
     *
     * @param id the value for t_work_order_template_info.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_work_order_template_info.template_name
     *
     * @return the value of t_work_order_template_info.template_name
     *
     * @mbggenerated
     */
    public String getTemplateName() {
        return templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_work_order_template_info.template_name
     *
     * @param templateName the value for t_work_order_template_info.template_name
     *
     * @mbggenerated
     */
    public void setTemplateName(String templateName) {
        this.templateName = templateName == null ? null : templateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_work_order_template_info.template_message
     *
     * @return the value of t_work_order_template_info.template_message
     *
     * @mbggenerated
     */
    public String getTemplateMessage() {
        return templateMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_work_order_template_info.template_message
     *
     * @param templateMessage the value for t_work_order_template_info.template_message
     *
     * @mbggenerated
     */
    public void setTemplateMessage(String templateMessage) {
        this.templateMessage = templateMessage == null ? null : templateMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_work_order_template_info.create_time
     *
     * @return the value of t_work_order_template_info.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_work_order_template_info.create_time
     *
     * @param createTime the value for t_work_order_template_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }
}
