package com.cmiot.rms.dao.model;

public class BusinessTemplateRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_business_template_relation.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_business_template_relation.manufacturerID
     *
     * @mbggenerated
     */
    private String manufacturerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_business_template_relation.manufacturer_name
     *
     * @mbggenerated
     */
    private String manufacturerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_business_template_relation.factoryID
     *
     * @mbggenerated
     */
    private String factoryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_business_template_relation.factory_name
     *
     * @mbggenerated
     */
    private String factoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_business_template_relation.gateway_model
     *
     * @mbggenerated
     */
    private String gatewayModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_business_template_relation.hd_version
     *
     * @mbggenerated
     */
    private String hdVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_business_template_relation.firmware_version
     *
     * @mbggenerated
     */
    private String firmwareVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_business_template_relation.business_template
     *
     * @mbggenerated
     */
    private String businessTemplate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_business_template_relation.bussiness_code
     *
     * @mbggenerated
     */
    private String bussinessCode;

    private String isIG;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_business_template_relation.id
     *
     * @return the value of t_business_template_relation.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_business_template_relation.id
     *
     * @param id the value for t_business_template_relation.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_business_template_relation.manufacturerID
     *
     * @return the value of t_business_template_relation.manufacturerID
     *
     * @mbggenerated
     */
    public String getManufacturerid() {
        return manufacturerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_business_template_relation.manufacturerID
     *
     * @param manufacturerid the value for t_business_template_relation.manufacturerID
     *
     * @mbggenerated
     */
    public void setManufacturerid(String manufacturerid) {
        this.manufacturerid = manufacturerid == null ? null : manufacturerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_business_template_relation.manufacturer_name
     *
     * @return the value of t_business_template_relation.manufacturer_name
     *
     * @mbggenerated
     */
    public String getManufacturerName() {
        return manufacturerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_business_template_relation.manufacturer_name
     *
     * @param manufacturerName the value for t_business_template_relation.manufacturer_name
     *
     * @mbggenerated
     */
    public void setManufacturerName(String manufacturerName) {
        this.manufacturerName = manufacturerName == null ? null : manufacturerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_business_template_relation.factoryID
     *
     * @return the value of t_business_template_relation.factoryID
     *
     * @mbggenerated
     */
    public String getFactoryid() {
        return factoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_business_template_relation.factoryID
     *
     * @param factoryid the value for t_business_template_relation.factoryID
     *
     * @mbggenerated
     */
    public void setFactoryid(String factoryid) {
        this.factoryid = factoryid == null ? null : factoryid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_business_template_relation.factory_name
     *
     * @return the value of t_business_template_relation.factory_name
     *
     * @mbggenerated
     */
    public String getFactoryName() {
        return factoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_business_template_relation.factory_name
     *
     * @param factoryName the value for t_business_template_relation.factory_name
     *
     * @mbggenerated
     */
    public void setFactoryName(String factoryName) {
        this.factoryName = factoryName == null ? null : factoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_business_template_relation.gateway_model
     *
     * @return the value of t_business_template_relation.gateway_model
     *
     * @mbggenerated
     */
    public String getGatewayModel() {
        return gatewayModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_business_template_relation.gateway_model
     *
     * @param gatewayModel the value for t_business_template_relation.gateway_model
     *
     * @mbggenerated
     */
    public void setGatewayModel(String gatewayModel) {
        this.gatewayModel = gatewayModel == null ? null : gatewayModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_business_template_relation.hd_version
     *
     * @return the value of t_business_template_relation.hd_version
     *
     * @mbggenerated
     */
    public String getHdVersion() {
        return hdVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_business_template_relation.hd_version
     *
     * @param hdVersion the value for t_business_template_relation.hd_version
     *
     * @mbggenerated
     */
    public void setHdVersion(String hdVersion) {
        this.hdVersion = hdVersion == null ? null : hdVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_business_template_relation.firmware_version
     *
     * @return the value of t_business_template_relation.firmware_version
     *
     * @mbggenerated
     */
    public String getFirmwareVersion() {
        return firmwareVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_business_template_relation.firmware_version
     *
     * @param firmwareVersion the value for t_business_template_relation.firmware_version
     *
     * @mbggenerated
     */
    public void setFirmwareVersion(String firmwareVersion) {
        this.firmwareVersion = firmwareVersion == null ? null : firmwareVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_business_template_relation.business_template
     *
     * @return the value of t_business_template_relation.business_template
     *
     * @mbggenerated
     */
    public String getBusinessTemplate() {
        return businessTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_business_template_relation.business_template
     *
     * @param businessTemplate the value for t_business_template_relation.business_template
     *
     * @mbggenerated
     */
    public void setBusinessTemplate(String businessTemplate) {
        this.businessTemplate = businessTemplate == null ? null : businessTemplate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_business_template_relation.bussiness_code
     *
     * @return the value of t_business_template_relation.bussiness_code
     *
     * @mbggenerated
     */
    public String getBussinessCode() {
        return bussinessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_business_template_relation.bussiness_code
     *
     * @param bussinessCode the value for t_business_template_relation.bussiness_code
     *
     * @mbggenerated
     */
    public void setBussinessCode(String bussinessCode) {
        this.bussinessCode = bussinessCode == null ? null : bussinessCode.trim();
    }

    public String getIsIG() {
        return isIG;
    }

    public void setIsIG(String isIG) {
        this.isIG = isIG;
    }
}