package com.cmiot.rms.dao.model;

public class BusinessCode extends BaseBean{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_business_code.business_code_boss
     *
     * @mbggenerated
     */
    private String businessCodeBoss;

    private String businessNameBoss;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_business_code.business_code_boss
     *
     * @return the value of t_business_code.business_code_boss
     *
     * @mbggenerated
     */
    public String getBusinessCodeBoss() {
        return businessCodeBoss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_business_code.business_code_boss
     *
     * @param businessCodeBoss the value for t_business_code.business_code_boss
     *
     * @mbggenerated
     */
    public void setBusinessCodeBoss(String businessCodeBoss) {
        this.businessCodeBoss = businessCodeBoss == null ? null : businessCodeBoss.trim();
    }

    public String getBusinessNameBoss() {
        return businessNameBoss;
    }

    public void setBusinessNameBoss(String businessNameBoss) {
        this.businessNameBoss = businessNameBoss;
    }
}