package com.cmiot.rms.dao.model;

public class GatewayPassword {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gateway_password.gateway_password
     *
     * @mbggenerated
     */
    private String gatewayPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gateway_password.order_no
     *
     * @mbggenerated
     */
    private String orderNo;


    private String adslAccount;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gateway_password.gateway_password
     *
     * @return the value of t_gateway_password.gateway_password
     *
     * @mbggenerated
     */
    public String getGatewayPassword() {
        return gatewayPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gateway_password.gateway_password
     *
     * @param gatewayPassword the value for t_gateway_password.gateway_password
     *
     * @mbggenerated
     */
    public void setGatewayPassword(String gatewayPassword) {
        this.gatewayPassword = gatewayPassword == null ? null : gatewayPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gateway_password.order_no
     *
     * @return the value of t_gateway_password.order_no
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gateway_password.order_no
     *
     * @param orderNo the value for t_gateway_password.order_no
     *
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

	public String getAdslAccount() {
		return adslAccount;
	}

	public void setAdslAccount(String adslAccount) {
		this.adslAccount = adslAccount;
	}

}