package com.cmiot.rms.dao.model;

public class GatewayBusinessOpenDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gateway_business_open_detail.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gateway_business_open_detail.business_code_boss
     *
     * @mbggenerated
     */
    private String businessCodeBoss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gateway_business_open_detail.gateway_uuid
     *
     * @mbggenerated
     */
    private String gatewayUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gateway_business_open_detail.open_status
     *
     * @mbggenerated
     */
    private String openStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gateway_business_open_detail.order_no
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gateway_business_open_detail.id
     *
     * @return the value of t_gateway_business_open_detail.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gateway_business_open_detail.id
     *
     * @param id the value for t_gateway_business_open_detail.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gateway_business_open_detail.business_code_boss
     *
     * @return the value of t_gateway_business_open_detail.business_code_boss
     *
     * @mbggenerated
     */
    public String getBusinessCodeBoss() {
        return businessCodeBoss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gateway_business_open_detail.business_code_boss
     *
     * @param businessCodeBoss the value for t_gateway_business_open_detail.business_code_boss
     *
     * @mbggenerated
     */
    public void setBusinessCodeBoss(String businessCodeBoss) {
        this.businessCodeBoss = businessCodeBoss == null ? null : businessCodeBoss.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gateway_business_open_detail.gateway_uuid
     *
     * @return the value of t_gateway_business_open_detail.gateway_uuid
     *
     * @mbggenerated
     */
    public String getGatewayUuid() {
        return gatewayUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gateway_business_open_detail.gateway_uuid
     *
     * @param gatewayUuid the value for t_gateway_business_open_detail.gateway_uuid
     *
     * @mbggenerated
     */
    public void setGatewayUuid(String gatewayUuid) {
        this.gatewayUuid = gatewayUuid == null ? null : gatewayUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gateway_business_open_detail.open_status
     *
     * @return the value of t_gateway_business_open_detail.open_status
     *
     * @mbggenerated
     */
    public String getOpenStatus() {
        return openStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gateway_business_open_detail.open_status
     *
     * @param openStatus the value for t_gateway_business_open_detail.open_status
     *
     * @mbggenerated
     */
    public void setOpenStatus(String openStatus) {
        this.openStatus = openStatus == null ? null : openStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gateway_business_open_detail.order_no
     *
     * @return the value of t_gateway_business_open_detail.order_no
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gateway_business_open_detail.order_no
     *
     * @param orderNo the value for t_gateway_business_open_detail.order_no
     *
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }
}