package com.cmiot.rms.dao.model;

public class HdVersionInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hd_version_info.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hd_version_info.hd_version
     *
     * @mbggenerated
     */
    private String hdVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hd_version_info.device_model
     *
     * @mbggenerated
     */
    private String deviceModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hd_version_info.device_id
     *
     * @mbggenerated
     */
    private String deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hd_version_info.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hd_version_info.id
     *
     * @return the value of t_hd_version_info.id
     *
     * @mbggenerated
     */

    private String description;

    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hd_version_info.id
     *
     * @param id the value for t_hd_version_info.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hd_version_info.hd_version
     *
     * @return the value of t_hd_version_info.hd_version
     *
     * @mbggenerated
     */
    public String getHdVersion() {
        return hdVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hd_version_info.hd_version
     *
     * @param hdVersion the value for t_hd_version_info.hd_version
     *
     * @mbggenerated
     */
    public void setHdVersion(String hdVersion) {
        this.hdVersion = hdVersion == null ? null : hdVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hd_version_info.device_model
     *
     * @return the value of t_hd_version_info.device_model
     *
     * @mbggenerated
     */
    public String getDeviceModel() {
        return deviceModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hd_version_info.device_model
     *
     * @param deviceModel the value for t_hd_version_info.device_model
     *
     * @mbggenerated
     */
    public void setDeviceModel(String deviceModel) {
        this.deviceModel = deviceModel == null ? null : deviceModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hd_version_info.device_id
     *
     * @return the value of t_hd_version_info.device_id
     *
     * @mbggenerated
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hd_version_info.device_id
     *
     * @param deviceId the value for t_hd_version_info.device_id
     *
     * @mbggenerated
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hd_version_info.create_time
     *
     * @return the value of t_hd_version_info.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hd_version_info.create_time
     *
     * @param createTime the value for t_hd_version_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}